### ISSUE TITLE
[BUG/FEATURE] - Feedback

### ISSUE THREAD

**Issue by mtwalsh** [markmead/alpinejs-sticky#2]
Hi Mark,

I took this for a spin on a project recently, thanks for sharing!

Couple of ideas/issues:

1. In my testing I found it didn't play nicely with a sticky element at the very top of the browser viewport. It would always trigger the `x-sticky` classes even if I was yet to scroll down the page, perhaps this was just my project though (I was hoping to find the time to setup a minimal test case). FWIW I had a play with both the root margin and threshold settings but I wasn't able to resolve it.

2. It would be nice to be able to configure some classes that get applied in the non-sticky state (and removed when sticky) and then some classes that are applied when the element is sticky, just so that I don't need to use `!important` classes to override existing ones.

**Comment by markmead** [comment]
Hi Matt 👋 Sorry for the delay, this slipped through the net while I've been focusing on HyperUI.

Thanks for the feedback, I'll start looking into the issue you highlighted. 

I like the idea of non-sticky state classes, it should be easy enough to add.

I'll keep you updated on the progress.

**Comment by markmead** [comment]
Hey, @mtwalsh here's PR #3 which adds the functionality, be good to get your thoughts, but no pressure.

**Comment by Lazerproof** [comment]
@markmead Wanted to test the new version, but there 1.1.1 version on NPM.

**Comment by markmead** [comment]
Hey, @Lazerproof that's odd... I've re-published `1.1.2`.
