### ISSUE TITLE
Flickering in latest Chrome (on Brave)

### ISSUE THREAD

**Issue by vladstudio** [markmead/alpinejs-sticky#5]
https://js.hyperui.dev/examples/utility-update-class-when-sticky opened in latest Brave browser (Chromium):

https://github.com/markmead/alpinejs-sticky/assets/914320/ed035b31-bc19-48e4-b454-71b253b0b2c2

**Comment by markmead** [comment]
Preview isn't the ideal viewing experience, can you try looking at the component code? There's a link in that warning.

**Comment by vladstudio** [comment]
Yeah the [link](https://js.hyperui.dev/components/utility-update-class-when-sticky.html) worked fine. Thanks.
